---
title: "climate_event"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(ncdf4)
library(lubridate)
library(plyr)
library(readr)
library(ggridges)

source("constants.R")
source("qair_to_vpd.R")
```

Dry_2009-2016


```{r}

#Create site data frame for climate extreme

#files <- Sys.glob("outputs/*")
fname <-"outputs/AU-Whr_2012-2016_OzFlux_Met_out.nc"
f <- nc_open(fname)
head(f)

#Extracting variables from ncdf file
cica <-ncvar_get(f, "cica")
t <- ncvar_get(f, "time")
tair <-ncvar_get(f, "Tair") - DEG_2_KELVIN
Fwsoil <-ncvar_get(f, "Fwsoil")
Prec <-ncvar_get(f, "Rainf") 
Prec <- Prec
qair <-ncvar_get(f, "Qair")
press <-ncvar_get(f, "PSurf")
vpd <- qair_to_vpd(qair, tair, press)

#Converting 'time_from' untis to min, hr, d, m, y values
time_from <- substr(ncatt_get(f, "time")$units, 15, 33) #
datetime <- as.POSIXct(t, origin=time_from, format = "%Y-%m-%d %H:%M")

#Creating data frame 


d_f <- data.frame(datetime, cica, tair, Prec, vpd, Fwsoil)
  colnames(d_f)<- c("datetime", "cica", "tair", "Prec", "vpd", "Fwsoil")
  d_f$year <- year(d_f$date)
  d_f$month <- month(d_f$date)
  d_f$week <- week(d_f$date)
  d_f$doy <- yday(d_f$date)
  d_f$hour <- hour(d_f$date)

  d_f <- d_f[d_f$cica > -500, ]
 
  
d_f_grp_month <- group_by(d_f, month) 
d_f_month <- summarize(d_f_grp_month, mean(cica))

d_f <- transform(d_f, month = month.abb[month])
d_f$month <-factor(d_f$month, 
                      levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun",
                                 "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))


```
```{r}
df_pre <- data.frame(datetime, Prec*86400)
  colnames(df_pre)<- c("datetime", "Prec")
  df_pre$year <- year(df_pre$date)
  df_pre$doy <- yday(df_pre$date)

  df_grp_doy <- group_by(df_pre, doy)
  df_doy <- summarize_all(df_grp_doy, funs(mean))
  

plot(df_doy$Prec)
```



```{r}


#Cica - Drought/ dry period 

 
  d_f$year <- factor(d_f$year)
   
  d_f %>% filter(year %in% c("2009", "2011", "2013", "2015", "2017")) %>%
  ggplot(aes(x=month, y=cica, group=year, color=year)) + 
  ylab(expression("Ci:Ca")) +
  xlab(expression("Month")) +
  geom_smooth(fill=NA)
 

  


```


```{r}
#drought- rainfall
d_f$year <- factor(d_f$year)

d_f %>% filter(year %in% c("2009", "2011", "2013", "2015")) %>%
ggplot(aes(x=month, y=Prec*86400/30, group=year, color=year)) + 
  ylab(expression("Mean Monthly Rainfall [mm]")) +
  xlab(expression("Month")) +
  geom_bar(stat="identity", aes(fill = year), position = "dodge")
```


```{r}
#drought VPD

d_f$year <- factor(d_f$year)

d_f %>% filter(year %in% c("2009", "2011", "2013", "2015")) %>%
ggplot(aes(x=month, y=vpd, group=year, color=year)) + 
  ylab(expression("VPD")) +
  xlab(expression("Month")) +
  geom_smooth(fill=NA)
```

```{r}
#drought fwsoil
d_f$year <- factor(d_f$year)

d_f %>% filter(year %in% c("2009", "2011", "2013", "2015")) %>%
ggplot(aes(x=month, y=Fwsoil, group=year, color=year)) + 
  ylab(expression("Fwsoil")) +
  xlab(expression("Month")) +
  geom_smooth(fill=NA)
```



```{r}
#Ci:Ca - heatwave 1-18 Jan 2013 (van Gorsel et al. 2016)

d_f$year <- factor(d_f$year)

d_f %>% filter(year %in% c("2013", "2014")) %>%
ggplot(aes(x=doy, y=cica, group=year, color=year)) + 
  ylab(expression("Ci:Ca")) +
  xlab(expression("Day of Year")) +
  geom_smooth(fill = NA) +
  xlim(1, 20)
```

```{r}
#Temp - heatwave 1-18 Jan 2013 (van Gorsel et al. 2016)

d_f$year <- factor(d_f$year)

d_f %>% filter(year %in% c("2013", "2014")) %>%
ggplot(aes(x=doy, y=tair, group=year, color=year)) + 
  ylab(expression("Temperature [° C]")) +
  xlab(expression("Day of Year")) +
  geom_smooth(fill = NA) +
  xlim(1, 20)
```

```{r}
d_f$year <- factor(d_f$year)

d_f %>% filter(year %in% c("2013", "2014")) %>%
ggplot(aes(x=doy, y=vpd, group=year, color=year)) + 
  ylab(expression("VPD")) +
  xlab(expression("Day of Year")) +
  geom_smooth(fill = NA) +
  xlim(1, 20)
```

```{r}
d_f$year <- factor(d_f$year)

d_f %>% filter(year %in% c("2013", "2014")) %>%
ggplot(aes(x=month, y=cica, group=year, color=year)) + 
  ylab(expression("Ci:Ca")) +
  xlab(expression("Month")) +
  geom_smooth(fill = NA)
```

```{r}
d_f$year <- factor(d_f$year)

d_f %>% filter(year %in% c("2013", "2014")) %>%
ggplot(aes(x=month, y=Prec*8640, group=year, color=year)) + 
  ylab(expression("Mean Monthy Rainfall [mm]")) +
  xlab(expression("Month")) +
  geom_bar(stat="identity", aes(fill = year), position = "dodge")
```

